In [39]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [40]:
df = sns.load_dataset('iris')

In [41]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [42]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [43]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [44]:
X = df.drop('species',axis = 1)
y = df['species']

In [45]:
X_train, X_test, y_train, y_test = train_test_split(
X, y, test_size=0.2, random_state=42)

In [46]:
from sklearn.neighbors import KNeighborsClassifier

In [84]:
model_knn = KNeighborsClassifier(n_neighbors=11)

In [85]:
model_knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=11)

In [86]:
model_knn.score(X_test,y_test)

1.0

In [50]:
from sklearn.svm import SVC

In [54]:
model_svm = SVC(kernel='linear')

In [55]:
model_svm.fit(X_train,y_train)

SVC(C=10, kernel='linear')

In [56]:
model_svm.score(X_test,y_test)

0.9666666666666667

# Grid Search CV

In [58]:
from sklearn.model_selection import GridSearchCV

In [59]:
classifier = GridSearchCV(model_svm,
{'C':[1,10,20],
 'kernel':['rbf','linear']},
cv=5,return_train_score=False)

In [60]:
classifier.fit(X,y)

GridSearchCV(cv=5, estimator=SVC(C=10, kernel='linear'),
             param_grid={'C': [1, 10, 20], 'kernel': ['rbf', 'linear']})

In [61]:
classifier.cv_results_

{'mean_fit_time': array([0.00505772, 0.00443168, 0.00488992, 0.00455155, 0.00473814,
        0.00411263]),
 'std_fit_time': array([8.17085141e-04, 7.21527891e-05, 8.30708446e-04, 4.27073834e-04,
        7.54763386e-04, 8.01158232e-05]),
 'mean_score_time': array([0.00347991, 0.00351853, 0.00370154, 0.00314999, 0.00306349,
        0.00303345]),
 'std_score_time': array([3.31475311e-04, 6.93821913e-04, 5.57518642e-04, 1.12360381e-04,
        9.70074074e-05, 5.50112627e-05]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20],
              mask=[False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'}],
 'split0_test_score': array([0.96666667, 0.96666667, 0.96666667, 1.        , 0.96666667,
        1.        ]),
 'split1_test_score': array([0.96666667, 1.        , 1.        , 1.        , 1.        ,
        1.        ]),
 'split2_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.9       , 0.96666667,
        0.9       ]),
 'split3_test_score': array([0.93333333, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.93333333]),
 'split4_test_score': array([1., 1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.96666667, 0.98      , 0.98      , 0.97333333, 0.98      ,
        0.96666667]),
 'std_test_score': array([0.02108185, 0.01632993, 0.01632993, 0.03887301, 0.01632993,
        0.0421637 ]),
 'rank_test_score': array([5, 1, 1, 4, 1, 5], dtype=int32)}

In [63]:
result = pd.DataFrame(classifier.cv_results_)
result

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.005058,0.000817,0.003480,0.000331,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.966667,0.966667,0.966667,0.933333,1.0,0.966667,0.021082,5
1,0.004432,0.000072,0.003519,0.000694,1,linear,"{'C': 1, 'kernel': 'linear'}",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.004890,0.000831,0.003702,0.000558,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
3,0.004552,0.000427,0.003150,0.000112,10,linear,"{'C': 10, 'kernel': 'linear'}",1.000000,1.000000,0.900000,0.966667,1.0,0.973333,0.038873,4
4,0.004738,0.000755,0.003063,0.000097,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
5,0.004113,0.000080,0.003033,0.000055,20,linear,"{'C': 20, 'kernel': 'linear'}",1.000000,1.000000,0.900000,0.933333,1.0,0.966667,0.042164,5

In [64]:
result[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0        1          rbf         0.966667
1        1       linear         0.980000
2       10          rbf         0.980000
3       10       linear         0.973333
4       20          rbf         0.980000
5       20       linear         0.966667

# With Knn

In [71]:
classifier_knn = GridSearchCV(model_knn,{
    'n_neighbors':[1,3,5,7,9,11,13,15,17,19,21,23,25],
    'weights':['uniform','distance'],
    'metric':['euclidean','manhattan','minkowski']
},cv=5,return_train_score=False)

In [72]:
classifier_knn.fit(X,y)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(n_neighbors=3),
             param_grid={'metric': ['euclidean', 'manhattan', 'minkowski'],
                         'n_neighbors': [1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21,
                                         23, 25],
                         'weights': ['uniform', 'distance']})